### ISSUE TITLE
Error with Parcel

### ISSUE THREAD

**Issue by daz4126** [WebReflection/uhtml#100]
Just got this error when trying to build with Parcel:

🚨 Build failed.

@parcel/core: Failed to resolve 'domconstants/constants' from 
'./node_modules/uhtml/esm/creator.js'

node_modules/uhtml/esm/creator.js:1:30
  > 1 | import { COMMENT_NODE } from 'domconstants/constants';
  >   |                              ^^^^^^^^^^^^^^^^^^^^^^^^
    2 | 
    3 | import { PersistentFragment } from './persistent-fragment.js';

@parcel/resolver-default: Cannot load file './constants' from module 'domconstants'

Any idea why that might be happening?

**Comment by WebReflection** [comment]
a bug with Parcel? Rollup has zero issues with proper ESM exports, so I have not much else to say about this issue.

**Comment by WebReflection** [comment]
to clarify, domconstants declares exports in the most modern/standard way and constants is part of such exports:
https://github.com/WebReflection/domconstants/blob/master/package.json#L24-L28

if Parcel is outdated or incapable to deal with the suggested way to export modules I am afraid there's not much I can do here, hence closing this issue, but feel free to ask more or write updates around it.

**Comment by daz4126** [comment]
Thanks. It probably is a problem with parcel. I’ll try using rollup instead.
