### ISSUE TITLE
4.8 breaks semver

### ISSUE THREAD

**Issue by drschwabe** [WebReflection/uhtml#108]
Minor detail but 4.7 to 4.8 by removing/replacing _reactive_ will break builds using that export.   I think it should be retained for bw compatiblity till 5.0 for example.

**Comment by WebReflection** [comment]
I am not sure I am following ... I didn't remove anything, I've added a `detach` feature ... did some file get lost in the process?

**Comment by WebReflection** [comment]
wait a minute ... are you referring to the fact it was a `default` export and now is not anymore?

I can add-back that default but it would break in *CJS* so I am not sure that's desired ... apologies though, I didn't think about it but I wanted to keep v5 for `hydro` whenever that happens (I'll try this Friday).

**Comment by WebReflection** [comment]
Nope ... I did break semver indeed ... patched and fixed now, apologies for causing troubles.

**Comment by drschwabe** [comment]
Yup, my bundle that was building in 4.7 but error'ed on 4.8 is now bundling AOK again in 4.9  
Thx!
