### ISSUE TITLE
SVG Uppercase Attribute Names Lowercased When Injecting Values

### ISSUE THREAD

**Issue by dwighthouse** [WebReflection/uhtml#11]
Create a normal SVG with a hard-coded `viewBox`, get correct output:
```
import {html, svg, render} from 'uhtml';
render(document.body, html`<svg viewBox="0 0 100 100" />`);
// Output in body: <svg viewBox="0 0 100 100"></svg>
```

Create an SVG with injected `viewBox` value, get lowercase `viewbox` attribute, which is invalid and is ignored by the browser, breaking the SVG:
```
import {html, svg, render} from 'uhtml';
const viewBoxText = '0 0 100 100';
render(document.body, html`<svg viewBox=${viewBoxText} />`);
// Output in body: <svg viewbox="0 0 100 100"></svg>
```

Using the svg function makes no difference here, still incorrect:
```
import {html, svg, render} from 'uhtml';
const viewBoxText = '0 0 100 100';
render(document.body, svg`<svg viewBox=${viewBoxText} />`);
// Output in body: <svg viewbox="0 0 100 100"></svg>
```

There are [dozens of SVG attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute) that require uppercase letters. Not sure how to proceed.

**Comment by dwighthouse** [comment]
Looks like it might have to do with the fact that attribute creation is using `document.createAttribute` here: https://github.com/WebReflection/uhtml/blob/a84b2510249bb145c54f59c0458fe401cb237026/index.js#L262

Which is brought in from uhandlers: https://github.com/WebReflection/uhandlers/blob/6ccc6a6ef19896911181d30fbd14a03075f56224/cjs/index.js#L12

```
const attr = document.createAttribute('viewBox');
// attr prints as 'viewbox=""'
```

However document.createAttributeNS can create the correctly named attribute with the right namespace:
```
const attr = document.createAttributeNS('http://www.w3.org/2000/svg', 'viewBox');
// attr prints as 'viewBox=""'
```

Or... maybe literally anything. These all produce the correctly capitalized attribute:
```
document.createAttributeNS('html', 'viewBox')
document.createAttributeNS('', 'viewBox')
document.createAttributeNS('xml', 'viewBox')
document.createAttributeNS(null, 'viewBox')
document.createAttributeNS(undefined, 'viewBox')
document.createAttributeNS('-//W3C//DTD XHTML 1.0 Strict//EN', 'viewBox')
document.createAttributeNS('-//W3C//DTD HTML 4.01 Transitional//EN', 'viewBox')
```

But it's not doing any kind of special processing or anything. It's just not lowercasing things:

```
const attr = document.createAttribute('html', 'VaLuE');
// attr prints as 'VaLuE=""'
```

**Comment by WebReflection** [comment]
so this is a _uhandlers_ issue, right? since we're here, do you know if using just `'html'` would have compatibility issues or it would actually work on SVG even if the attribute was created for a different namespace?

**Comment by WebReflection** [comment]
This should've been fixed.

**Comment by dwighthouse** [comment]
I'm afraid it's not fixed, though I don't blame you for thinking it is. I tried out the new version, 1.11.2, and while the element output text looks ok, the data backing it seems to be wrong in a way I've never seen before.

Somehow, the attributes applied don't get applied to the data of the dom node, only as "random" attributes of no meaning:
```
import {html, svg, render} from 'uhtml';
const viewBoxText = '0 0 100 100';
render(document.body, html`
    <svg viewBox=${viewBoxText} style=${`width: ${1000}px; height: ${1000}px;`}>
        <rect x="0" y="0" width="50" height="50" fill="#f00" />
    </svg>
`);
// element.style shows up with the entered values in the Developer Tools
// However the actual DOM values don't correspond anymore...

const realWidth = document.querySelector('svg').clientWidth;
// 300 - default, wrong

const realHeight = document.querySelector('svg').clientHeight;
// 150 - default, wrong

// Manually set style
document.querySelector('svg').style.width = '2000px';

const newWidth = document.querySelector('svg').clientWidth;
// 2000 - correct

const htmlOutput = document.querySelector('svg').outerHTML;
// <svg viewBox="0 0 100 100" style="width: 1000px; height: 1000px;" style="width: 2000px;"><rect x="0" y="0" width="50" height="50" fill="#f00"></rect></svg>
// TWO STYLE ATTRIBUTES?!
```

Not pictured in this example, but other attributes are being damaged too. My actual SVG that I implemented in my real project doesn't render anything, all elements having a size of 0 x 0, possibly because their dimension data is not being set correctly.

Compare this to doing it manually:

```
const viewBoxText = '0 0 100 100';

document.body.innerHTML = `
    <svg viewBox="${viewBoxText}" style="${`width: ${1000}px; height: ${1000}px;`}">
        <rect x="0" y="0" width="50" height="50" fill="#f00" />
    </svg>
`;

const realWidth = document.querySelector('svg').clientWidth;
// 1000 - correct

const realHeight = document.querySelector('svg').clientHeight;
// 1000 - correct

// Manually set style
document.querySelector('svg').style.width = '2000px';

const newWidth = document.querySelector('svg').clientWidth;
// 2000 - correct

const htmlOutput = document.querySelector('svg').outerHTML;
// <svg viewBox="0 0 100 100" style="width: 2000px; height: 1000px;"><rect x="0" y="0" width="50" height="50" fill="#f00"></rect></svg>
// Nothing weird here
```

**Comment by dwighthouse** [comment]
> since we're here, do you know if using just 'html' or null would have compatibility issues or it would actually work on SVG even if the attribute was created for a different namespace?

I'm afraid that the interactions of namespaces with attributes and such is beyond my knowledge of the spec.

**Comment by WebReflection** [comment]
I believe this is now fixed.

**Comment by WebReflection** [comment]
live page here: https://webreflection.github.io/uhtml/test/svg.html

**Comment by dwighthouse** [comment]
@WebReflection Thanks so much! Everything seems to be working correctly now.
