### ISSUE TITLE
Type definitions are buggy

### ISSUE THREAD

**Issue by iacore** [WebReflection/uhtml#111]
```
❯ cat node_modules/uhtml/./types/dom/index.d.ts
import Document from './document.js';
import DOMParser from './dom-parser.js';
export { Document, DOMParser };
```

`./document.js` does not even exist. It should be `./document.d.ts` afaik.

uhtml/init and uhtml/dom have this problem. Maybe they all have this problem.

**Comment by WebReflection** [comment]
it's tsc generating those though ... https://github.com/WebReflection/uhtml/blob/main/package.json#L17 ... 🤔

**Comment by iacore** [comment]
I removed all `"types":....` lines from `package.json` and the types immediately works in VSCode.

JSDoc is better. Typescript LSP recognize that.

- Ctrl+Click jump to source code, not .d.ts
- 1 less build step

For more details, see [Why Svelte did TS->JSDOC](https://github.com/sveltejs/svelte/pull/8569).

**Comment by iacore** [comment]
I was using `uhtml/init` and `uhtml/dom` in [my project](https://git.envs.net/iacore/data-soup), and the types was buggy. I'll fix it.
