### ISSUE TITLE
Error When Removing Attributes on SVGs (possibly other elements)

### ISSUE THREAD

**Issue by dwighthouse** [WebReflection/uhtml#12]
According to the [documentation](https://github.com/WebReflection/uhtml/blob/master/DOCUMENTATION.md), an attribute can be removed from an element by setting its value to null or undefined. When attempting to do this with an SVG element, such as `rect` with a `mask`, uhtml attempts to call a non-existent function, `removeAttributeNodeNS`.

The specific error is: `Uncaught TypeError: t.removeAttributeNodeNS is not a function`

There are namespace-capable [attribute removal functions](https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttribute#Usage_notes), but not that one.

Here's a minimal example showing the issue:

```
import {svg, render} from 'uhtml';

let doMask = true;

const renderSvg = () => {
    return svg`
        <svg viewBox="0 0 100 100" style="width: 100px; height: 100px;">
            <mask id="mask">
                <rect
                    x="50"
                    y="50"
                    width="50"
                    height="50"
                    fill="#fff" /></rect>
            </mask>
            <rect
                x="0"
                y="0"
                width="100"
                height="100"
                mask=${doMask ? 'url(#mask)' : null}
                fill="#f00" /></rect>
        </svg>
    `;
}

render(document.body, renderSvg());

doMask = false;

render(document.body, renderSvg());
```

**Comment by WebReflection** [comment]
Thanks. It's fixed now.

**Comment by dwighthouse** [comment]
Thanks!

**Comment by WebReflection** [comment]
no, thank you, it was a bit naive of me to think that method existed in the first place, and my tests should've found that ... sadly they didn't, as I'm using basichtml which implemented, erroneously, that method.
