### ISSUE TITLE
Render unsafe content with V4

### ISSUE THREAD

**Issue by remyguillaume** [WebReflection/uhtml#126]
Hello,

I'm migrating to V4.

In V3, we were using the possibility to render unsafe content described at the end of the documentation : 
https://webreflection.github.io/uhtml/

```
import { render, html, svg } from 'uhtml';

const htmlUnsafe = str => html([str]);
const svgUnsafe = str => svg([str]);

render(document.body, htmlUnsafe('<h1>Hello HTML</h1>'));
```

But this doesn't seem to work any more, I get a typescript error :

```
Argument of type 'string[]' is not assignable to parameter of type 'TemplateStringsArray'.
  Property 'raw' is missing in type 'string[]' but required in type 'TemplateStringsArray'
```

Could you please let me know how I should now do this with the new version?

Many thanks,
Guillaume.

**Comment by WebReflection** [comment]
did you move from plain JS to TS in the meantime? that error has nothing to do with the library, it's a TS issue

**Comment by remyguillaume** [comment]
No, the project was already in typescript.

If I take the exemple from docu:

```
import { render, html, svg } from 'uhtml';

const htmlUnsafe = str => html([str]);
const svgUnsafe = str => svg([str]);

render(document.body, htmlUnsafe('<h1>Hello HTML</h1>'));
```

With V3, str could be a simple string. And it worked.
Now str cannot be a simple string any more, it has to be a TemplateString.
And if I ignore the type checking (with ts-ignore), it does not work any more, my string is not rendered unsafe.

Actually, the documentation seems to be wrong now.  The code from the example is not valid in typescript any more.

**Comment by remyguillaume** [comment]
Sorry, I said something wrong: Actually it's still working when you ignore the type-checking.

What would be the consequence of allowing string arrays for the html method ?

```
export const html: (template: TemplateStringsArray | string[], ...values: Value[]) => Hole;
```

instead of 

```
export const html: (template: TemplateStringsArray, ...values: Value[]) => Hole;
```

**Comment by WebReflection** [comment]
imho unsafe evaluation is rally something people should *not* do + all optimizations fail with the uniqueness of the array so I am actually kinda happy this pattern is discourage from *TS* and **maybe** explicitly documenting that passing `['unsafe html'] as TemplateStringsArray` is the way to go? Does that work in TS?

**Comment by remyguillaume** [comment]
Hi, 

Thanks or your answer.

I generally agree with you, this should be avoided as much as possible, because it can have some performance and security implications.
But there are some usecases where you just come back to legacy-part of your infrastructure, and where you should be able to display HTML link that has been saved in your database as HTML code directly, for example. For those specific cases we need to find a solution.

I've find a workaround where I do not have to use `ts-ignore`:

```
htmlUnsafe(str: string) {
  const templatedString = [str] as unknown as TemplateStringsArray;
  return html(templatedString);
}
```

Remark : you need the dobble cast here (`as unknown as TemplateStringsArray`).

It's not ideal, but it works and with it you do not have a typescript error any more.
I think it would do the trick for me.
Thanks again.

**Comment by WebReflection** [comment]
@remyguillaume I would still improve / optimize that ... if it's a one-off it's OK but if it's not:

```ts
const cache = new Map<string, TemplateStringsArray>;

const add = (str: string) => {
  const template = [str] as unknown as TemplateStringsArray;
  cache.set(str, template);
  return template;
};

const unsafe = (str: string) => cache.get(str) || add(str);

// example:
// render(document.body, html(unsafe('<h1>Hello</h1>')))
```

You could add a *FinalizationRegistry* to the equation and free that cache when the `template` is not needed anymore and I suggest [gc-hook](https://github.com/WebReflection/gc-hook) for that:

```js
import { create } from 'gc-hook';

const onGC = str => cache.delete(str);
```

at that point your `add` utility would look like this:

```ts
const add = (str: string) => {
  const template = [str] as unknown as TemplateStringsArray;
  cache.set(str, template);
  return create(str, onGC, { return: template, token: false });
};
```

When the template won't be used anymore, it can be safely removed from the `cache` avoiding leaks in the long run.

**Comment by remyguillaume** [comment]
Thanks for the further infos and remarks.

I will implement the caching, that's a good tip.

As the usage of unsafe is really limited in our application, I think I won't integrate the gc-hook for now. In the worste case we will have 100 to 200 strings in memory, and even it your comments make totaly sense, adding a new dependency in the project just for this case looks a bit overkill and bring more complexity and risks for the moment.

But I'll add a note about this for sure!
Thanks again!

One last info : If you wish to list somewhere the projects depending on uHtml, you could add a link to https://gitlab.com/geogirafe/gg-viewer, if you want to :)
