### ISSUE TITLE
Message about package.json's export during esbuild build

### ISSUE THREAD

**Issue by archiloque** [WebReflection/uhtml#128]
Hello, 

when building a project that use uhtml with esbuild, I get these messages:

```

● [DEBUG] The condition "require" here will never be used as it comes after "default" [package.json]

    node_modules/uhtml/package.json:52:8:
      52 │         "require": "./types/index.d.cts"
         ╵         ~~~~~~~~~

  The "default" condition comes earlier and will always be chosen:

    node_modules/uhtml/package.json:51:8:
      51 │         "default": "./types/index.d.mts",
         ╵         ~~~~~~~~~

● [DEBUG] The condition "types" here will never be used as it comes after "default" [package.json]

    node_modules/uhtml/package.json:50:6:
      50 │       "types": {
         ╵       ~~~~~~~

  The "default" condition comes earlier and will always be chosen:

    node_modules/uhtml/package.json:49:6:
      49 │       "default": "./cjs/index.js",
         ╵       ~~~~~~~~~
```

they don't seem the impact the result but they are rather annoying.

See [here](https://github.com/prisma/prisma/issues/25044) for another instance.

I had a look at the issue and the message seem correct, for example [here](https://nodejs.org/api/packages.html) "default - the generic fallback that always matches. Can be a CommonJS or ES module file. This condition should always come last."

It seems that the fix would be to invert the `require` and `default` lines. If you agree that a fix is worthy I can create a PR.

Thanks !

**Comment by WebReflection** [comment]
works for me

**Comment by WebReflection** [comment]
@archiloque up and running 🥳
