### ISSUE TITLE
Question: How to avoid duplicating work in uhtml?

### ISSUE THREAD

**Issue by dwighthouse** [WebReflection/uhtml#13]
I think I misunderstand the purpose of `html.for()`. I'm attempting to avoid unnecessary work on rerender. Right now, if given a list of 1000 items, upon changing just one of them, the entire 1000 items will rerender. Or at least their render functions will run unnecessarily. DOM manipulation may only be limited to the item that changed.

Coming from a React background, it's fairly easy to avoid entire render trees if the props of the parents did not change. How do you suggest avoiding rerenders of nested components when their input data does not change? Is there a uhtml-specific way? Or is the solution to roll my own memoizer? I'm just not sure how I should be approaching the problem.

Secondarily, but related, how do you suggest we implement nested components that themselves do not generate html, but only help prepare child components to render? Right now, I'm creating an unnecessary template string with a single value in it:

```javascript
const HelperComponent = (item, index) => {
    const computedIndex = index + 1;
    return html.for(item)`${ChildComponent(item, index, computedIndex)}`;
};
```

Admittedly, my approach is very component-centric given my React background. Is this an inappropriate approach to use when using uhtml?

I've created a jsfiddle to demonstrate the question: https://jsfiddle.net/8dk5x4wr/1/

And the code for it is duplicated below:

```html
<!doctype html>
<title>List</title>

<div id="root"></div>

<script src="https://unpkg.com/uhtml@1.11.6/min.js"></script>
<script>
const { html, render } = uhtml;

const appState = {
    list: [],
};

const root = document.getElementById('root');

// Initialize state
for (let i = 0; i < 1000; i += 1) {
    appState.list.push({
        id: i,
        text: `Item ${i + 1}`,
        checked: false,
    });
}

const ListItem = (item, index, onChangeCheckboxAt) => {
    // Every time one checkbox is clicked, 1000 ListItems rerender (or at least their render functions run, duplicating unnecessary work)
    console.log('Some expensive calculation');

    const onChangeCheckbox = () => {
        onChangeCheckboxAt(!item.checked, index);
    };

    return html`
        <li>
            <label>
                <input type="checkbox" onChange=${onChangeCheckbox} .checked=${item.checked} />
                ${item.text}
            </label>
        </li>
    `;
};

const onChangeCheckboxAt = (value, index) => {
    // Immutably update list while retaining old item references
    appState.list = [
        ...appState.list.slice(0, index),
        {
            ...appState.list[index],
            checked: value,
        },
        ...appState.list.slice(index + 1),
    ];

    // Rerender
    render(root, App(appState));
};

const App = (state) => {
    return html`
        <div>
            <h1>My List</h1>

            <ul>
                ${state.list.map((item, index) => {
                    // How do I render a child component that doesn't require surrounding html?
                    // Right now, I have to surround it in a meaningless template string.
                    // Also, because the function for ListItem is called immediately in order to inject it into the template string,
                    //   it is evaluated immediately, doing unnecessary work for items that have not changed
                    // How do we tell uhtml "use the results of the last render instead of running this component again?"
                    return html.for(item)`${ListItem(item, index, onChangeCheckboxAt)}`;
                })}
            </ul>
        </div>
    `;
};

// Startup
render(root, App(appState));
</script>
```

**Comment by WebReflection** [comment]
I think the misunderstanding is how template literals work here:

```js
const HelperComponent = (item, index) => {
    const computedIndex = index + 1;
    return html.for(item)`${ChildComponent(item, index, computedIndex)}`;
    // it's *you* invoking the function ^^^^ how is any library supposed to avoid that?
};
```

If you explicitly invoke any function that will be executed. _uhtml_ role is to avoid unnecesary DOM manipulation for nodes that didn't change, and that's it ... how you pass interpolated values to each "_hole_" it's just your business, and if you invoke a function you just ... well ... invoke a function, right?

With _uhtml_ you define the view, that's it. If you have a state associated uniquely with a view, that's when you use `html.for(ref[, id])`, but in a template literal, values are retrieved regularly, so that invoking anything, will result into invoking that anything.

Since you come from React, you might consider 3 alternatives:
  * [neverland](https://github.com/WebReflection/neverland/#readme)
  * [heresy](https://github.com/WebReflection/heresy/#readme)
  * [uce](https://github.com/WebReflection/uce/#readme)

The latter is based on Custom Elements, so you define their name and you pass them as `<my-el>` ... others are similar to React, hence maybe easier for you to grasp.

**Comment by dwighthouse** [comment]
I'm aware why it is happening in my demo. I mentioned as much in the comment:

> "Also, because the function for ListItem is called immediately in order to inject it into the template string, it is evaluated immediately, doing unnecessary work for items that have not changed".

The question is: what is the appropriate way to avoid this? Yes, this may not be something implemented by uhtml, but it is a common problem that needs to be understood in the context of using any front end rendering framework.

From what I can see, it comes down to the fact that uhtml accepts as input to a Hole the *results* of a rendering of html, but not a function that *will result* in a rendering of html, if called.

I attempted to convert my demo to neverland, but failed. It looks like the version on unpkg and the various versions in your repository don't match. Either way, I don't understand how converting to neverland will actually answer the question I asked. As for uce, I am not interested in browser-based custom elements. I only need to be able to separate different rendering aspects of my app into logical components.

**Comment by dwighthouse** [comment]
Upon further reflection, I realized that the solution must be in some form of memoization. I will explore that.

**Comment by dwighthouse** [comment]
Premature optimization strikes again!

On a whim, I used the "fastest memoizer" in JS with my project to memoize the list items in my actual project, not this simplified demo. And I also implemented my actual project in optimized React. And all that compared to plain uhtml, minus a couple of bugs I had introduced earlier (namely, unnecessarily calling `html.node`).

Adding memoization to uhtml made everything slower by about 100 times. Clearly, I would have to do tremendously expensive operations in every render to make memoization worth it for uhtml renders.

Optimized React + Memoization is about 2 to 3 times faster at making updates than plain uhtml. This isn't saying much, as the difference between them is less than 10 milliseconds. Additionally, React's the startup time is about 5 times slower, though my crude test in React does a lot more during its startup than the bare bones uhtml project I have.

I do still wonder if there is a way to indicate to uhtml when exactly one item in a list changed, and which one, to somehow avoid even the partial operations on the unchanged values. But that's for another time.

**Comment by WebReflection** [comment]
The reason I've mentioned _neverland_ is that it's been created to define components as functions, and it offers `useMemo` and other React like hooks out of the box.

However, if that's not what you want to do, I suggest using _umap_ and call it a day:
```js
import umap from 'umap';
const memo = umap(new WeakMap);
const HelperComponent = (item, index) => {
    const computedIndex = index + 1;
    return memo.get(item) || memo.set(
      item,
      html.for(item)`${ChildComponent(item, index, computedIndex)}`
    );
};
```

In above case you ensure you return the computed node related to `item` once.

Alternatively, your `ChildComponent` could avoid the expensive operation or cache its result using a similar approach:
```js
const expensiveResults = new WeakMap;
const ListItem = (item, index, onChangeCheckboxAt) => {
		if (!expensiveResults.has(item)) {
    	expensiveResults.set(item, {expensive: 'result'});
    	console.log('Some expensive calculation');
    }

    const onChangeCheckbox = () => {
        onChangeCheckboxAt(!item.checked, index);
    };
    // I still suggest to use `html.for(item)` here, but it's probably not needed
    // unless yoi have Custom Elements in the mix, which doesn't seem to be the case
    return html`
        <li>
            <label>
                <input type="checkbox" onChange=${onChangeCheckbox} .checked=${item.checked} />
                ${item.text}
            </label>
        </li>
    `;
};
```

The fact an optimized version of React performs better than a library which patterns are different, is not really a surprise to me, but in every benchmark you can find out there, _uhtml_ outperform React by a 5x to 20x+ margin, so maybe it's simply a matter of finding a better pattern for _uhtml_?

**Comment by WebReflection** [comment]
P.S. with _umap_, that would be:

```js
const results = umap(new WeakMap);
const ListItem = (item, index, onChangeCheckboxAt) => {
    const result = results.get(item) ||
                          results.set(item, console.log('Some expensive calculation'));

    const onChangeCheckbox = () => {
        onChangeCheckboxAt(!item.checked, index);
    };
    // I still suggest to use `html.for(item)` here, but it's probably not needed
    // unless yoi have Custom Elements in the mix, which doesn't seem to be the case
    return html`
        <li>
            <label>
                <input type="checkbox" onChange=${onChangeCheckbox} .checked=${item.checked} />
                ${item.text}
            </label>
        </li>
    `;
};
```

**Comment by dwighthouse** [comment]
Thanks @WebReflection ! That was what I was looking for. With the new construction, there's a small initial startup cost (smaller than React), but updates in uhtml are now significantly faster than optimized React.
