### ISSUE TITLE
Textarea with state based content

### ISSUE THREAD

**Issue by Spope** [WebReflection/uhtml#17]
Hi,
First thanks for uhtml ! 
Second, I'd say this is more of a question than a bug. I tried to create a textarea and make it state based. My first try was to add an `onkeyup` on my textarea to update my state value and display this state into my textarea. [codepen](https://codepen.io/Spope/pen/RwrGRrw?editors=1010)
With `onkeyup`, textarea is updated before uhtml is called to re-render it and when I empty my state, it looks like a reference is lost.
Then I tried the `onkeydown` [codepen](https://codepen.io/Spope/pen/BajLraj?editors=1010) with a `event.preventDefault()` to cancel textarea update. Then uhtml correctly render state value and empty it.
I guess I should use `document.querySelector(..).value` in this case but wanted to know if I missed something here.

**Comment by WebReflection** [comment]
I think what you want there is to use the value, like you'd do with an input:

```js
import {render, html} from 'https://unpkg.com/uhtml?module';

var text = "Hi";

const update = function(e) {
  text = e.currentTarget.value;
  refresh();
  e.preventDefault();
}

const resetText = function() {
  text = '';
  refresh();
}

const refresh = () => {
  render(document.querySelector('#content'), html`
    <h1>${text}</h1>
    <textarea onkeyup=${update} value=${text} />
    <button onclick=${resetText}>Reset</button>
  `);
}

refresh();
```

this works for me, on keyup/down anything 👋

**Comment by Spope** [comment]
Ok sure, looks obvious now... 
Just to be correct, I'd say you forgot the dot before the `value` attribute in the snippets.

Thanks for your answer !

**Comment by WebReflection** [comment]
the dot in this case is not necessary, and the guard is different: attributes don't get changed at all if the value is the same (i.e. you just press arrow to move the cursor) while `.value=${...}` would invoke the setter every single time, which might be a waste of CPU if the browser is not smart about it.

**Comment by Spope** [comment]
Hum, without the dot, the attribute value is indeed correct but the diplayed content of the textarea is not.
It's empty on first render, and doesn't reset once updated.

**Comment by WebReflection** [comment]
@Spope use the dot then, I probably haven't paid enough attention to this detail, apologies.
