### ISSUE TITLE
Question: how to render async inside template

### ISSUE THREAD

**Issue by sladiri** [WebReflection/uhtml#20]
I see that only hyperHTML can render a promise inside a template.

How would I render a template which has another template but as a Promise?

**Comment by WebReflection** [comment]
this projects renders any asynchronous chunk of the page through promises:
https://github.com/WebReflection/hn

the live version is here:
https://webreflection.github.io/hn/top/?1

TL;DR ... whenever you resolve a promise, re-render again, it's gonna be fine 👍

**Comment by WebReflection** [comment]
more details here: https://medium.com/@WebReflection/an-isomorphic-hacker-news-pwa-a26c3b9adf2c

TL;DR you don't need promises within holes, as the performance of re-rendering these are just fine

**Comment by sladiri** [comment]
Thank you for you response. The standards approach looks very nice.

**Comment by sladiri** [comment]
Just to explain, I am just re-rendering in a small new project I am working on. The re-rendeing uses async generators, similar to what is described here: https://crank.js.org/blog/introducing-crank

**Comment by sladiri** [comment]
Not sure if you would get email updates on edits of my comments, sorry if my multiple replies are not needed.
I am basically doing the same thing with what you do with the `fx`  function but async. And my question was about how to have multiple of such "update-queues" in a page. Your example only has one. But I found it is not hard to do, if a parent awaits a promise of its children before calling updatePage. Again, only one parent at the top of the async tree calls updatePage, as you do.
