### ISSUE TITLE
input element does not show updated value

### ISSUE THREAD

**Issue by sladiri** [WebReflection/uhtml#21]
I have a stackblitz here: https://codepen.io/sladiri/pen/gOPdjee 

If you change the value via the spinners and then click the reset button, the input stays the same, although the value changed. It happens with text input as well.

**Comment by WebReflection** [comment]
it's `.value=${...}`, as you want to change the value, not set just the attribute 👋

**Comment by sladiri** [comment]
Thank you very much for the explanation, I missed that.

**Comment by WebReflection** [comment]
To extend the explanation, this is how the DOM works, no library used:

```js
document.body.innerHTML = `<input value="before">`;
"<input value=\"before\">";
document.body.firstElementChild.value = 'after';
document.body.firstElementChild.value; // "after"
document.body.firstElementChild.getAttribute('value'); // "before"
```

the attribute does not reflect the value you'd set via JS, it's always the same attribute 👋
