### ISSUE TITLE
Script tags generated with uhtml do not execute when appended

### ISSUE THREAD

**Issue by dbauszus-glx** [WebReflection/uhtml#22]
I am in the process of replacing hyperhtml with microhtml in my library. This works great apart from one tiny thing which I cannot work out.

I used to add script tags with hyperhtml which would execute when appended. This doesn't seem to work with microhtml.

I created a small codepen to test the behaviour.

https://codepen.io/dbauszus-glx/pen/MWyYQWK

I created an alert('foo') script which I put on my github pages.

https://geolytix.github.io/public/foo.js

This will execute the script.

```
  .appendChild(
    hyperHTML.wire()`<script src="https://geolytix.github.io/public/foo.js">`
  );
```

But this won't.

```
  .appendChild(
    html.node`<script src="https://geolytix.github.io/public/foo.js">`
  );
```

Is this a bug or am I doing something wrong with uhtml?

**Comment by WebReflection** [comment]
differently from hyperHTML, uhtml is secure by default, and scripts are not allowed.

However, you can try to make scripts alive after you render any node, here another attempt that was apparently successful:

https://github.com/WebReflection/uhtml/issues/18#issuecomment-644855888

P.S. I do not recommend these things, as it's too easy to enable XSS 👋
