### ISSUE TITLE
Setting boolean attributes (e.g. checked on checkbox type input)

### ISSUE THREAD

**Issue by dbauszus-glx** [WebReflection/uhtml#23]
Should it be possible to set boolean attributes like checked on a checkbox type input with template literals in uhtml?

This works:
```
render(document.getElementById('chk'), html`
<input
  type="checkbox"
  checked
  onchange=${e => {
    console.log(e.target.checked);
}}>`)
```

But this fails:
```
const isChecked = true

render(document.getElementById('chk'), html`
<input
  type="checkbox"
  ${isChecked && 'checked'}
  onchange=${e => {
    console.log(e.target.checked);
}}>`)
```

I created a codepen for this. https://codepen.io/dbauszus-glx/pen/xxVzjdb

**Comment by dbauszus-glx** [comment]
Not to worry. I found an answer here... https://github.com/WebReflection/uhtml/issues/12

This is solved by setting checked to be null or true like so:

```
render(
  document.getElementById("chk"),
  html` <input
    type="checkbox"
    checked=${isChecked && "checked" || null}
    onchange=${(e) => {
      console.log(e.target.checked);
    }}
  />`
);
```

**Comment by WebReflection** [comment]
`checked` is a boolean attribute, you want to put a dot in front:

```js
render(
  document.getElementById("chk"),
  html` <input
    type="checkbox"
    .checked=${isChecked}
    onchange=${(e) => {
      console.log(e.target.checked);
    }}
  />`
);
```

**Comment by WebReflection** [comment]
It's in here https://github.com/WebReflection/uhtml#api-documentation

check **attributes** section ... I wish people read that tiny API in the README before filing issues 😅

**Comment by semmel** [comment]
@dbauszus-glx Thanks for asking this. This is useful to know. 
I could not make the connection myself that "invoking the known setter" with a Boolean essentially removes/creates that attribute. (As is written in the docu).

@WebReflection Thanks for the awesome lib!
