### ISSUE TITLE
Question: Live layout + style + values + input

### ISSUE THREAD

**Issue by dumblob** [WebReflection/uhtml#25]
Hi, I'm coming from a bit different background (long-running reliable distributed systems), so bear with me in this context of web development as I'll think of it differently than genuine web devs.

I'm looking at different projects which could fit in the following use case and uhtml with other libs in the wild seems so far the best I could find IMHO.

I envision having a server and client whereas server persists everything going through it (both in & out). Both server and client are nearly not limited, so I'd highly prefer using most modern technologies. Backward compatibility is a non-goal and I'm fine with supporting only one web browser (e.g. Chromium).

Any event the server will generate (e.g. in response to disk corruption) will be immediately sent (multiplexed aka "muxed") to all currently connected clients. Any event client will generate (e.g. user pressed a button or wrote a character to text input) shall be immediately sent to the server and the server shall first validate the event (incl. authorization, data integrity, ...), then process it, then persist the outcome (e.g. the pressed button changed label so the server shall since that very moment server only the new label on that button to all clients) and then distribute ("push") the changed of the state (in this case the new label) to all currently connected clients and all these clients shall in response to the push change the button label (note that any newly connected clients afterwards will already get the new button label as it got persisted and won't need any such "patches" to be sent around).

So far I thought that the communication channel between server and clients could be a websocket (to maintain the connection state and make muxing presumably easy) and that the server could be *fastify* (with fastify-websocket) and on the client *uhtml* with [concur-js](https://github.com/ajnsit/concur-js ).

But I'm struggling deciding how the data to be sent over the websocket channel should look like. I'd naturally expect to have two types of messages from server to client (s2c) and one type of messages from client to server (c2s). For s2c it'd be "keyframes" (i.e. whole HTML to be rendered by client whereas client would take it and render as is) and "patches" (i.e. just parts of an already rendered HTML whereas client would apply these patches). For c2s it'd be only "requests for patch" with "version of the HTML on the client with which the request was generated" (server could e.g. choose to not satisfy the request if the version would be different than the latest version in the given s2c connection queue if the queue is not empty by the time the request arrived). The "keyframes" would be sent e.g. when a new client connected to the web server (incl. forced reload). Otherwise only "patches" and "requests for patches" would be sent.

In this architecture I'm not sure how to generate the diffs on server and how to apply them on client. uhtml (or maybe [ucontent](https://github.com/WebReflection/ucontent ) similarly to [Isomorphic Hacker News](https://github.com/WebReflection/hn )?) doesn't seem to have any API allowing creation (and later their application) and (de)serialization of patches for transfer over a websocket.

(other, but slow and missing features, alternatives could be https://github.com/ms-jpq/noact and https://github.com/zserge/o )

Judging based on https://github.com/WebReflection/uhtml/issues/20 it doesn't seem impossible, but I'll rather take advice from an expert than banging my head in the future :wink:.

**Comment by WebReflection** [comment]
well, if it's just data, as in button label, it would look like this:

```js
const Button = ({label}) => html`<button>${label}</label>`;
```

and in such case as soon as the data is different, a new render will visualize the new label ... this is easy, but if it's about structural changes, you need some indirection, and [tag-params](https://github.com/WebReflection/tag-params#readme) looks like the best tool for this job.

```js
import {render, html} from 'uhtml';
import {partial} from 'tag-params';

const cache = new Map;
const set = layout => {
  const view = partial(layout);
  cache.set(layout, view);
  return view;
};

const Button = ({layout, data}) => {
  const view = cache.get(layout) || set(layout);
  return html.apply(null, view(data));
};

const info = {
  layout: '<button>${label}</label>',
  data: {label: 'Hello Partials!'}
};

render(document.body, Button(info));
```

At this point the button related _info_ can change both data and layout at any time, and a new render would simply pick that up when it's different.

You can see a [live demo in codepen](https://codepen.io/WebReflection/pen/QWNzrEw?editors=0010), where after two seconds the button becomes something else.

I hope this answers/helps, and I'm closing this as non-issue but feel free to ask more, if needed 👋

**Comment by dumblob** [comment]
Wow, it seems even slightly simpler than I thought because I didn't realize *uhtml* and your libs around are basically another take on [immediate mode UI](https://github.com/Immediate-Mode-UI/ ) generation mixed with some retained state like in [layout.c](https://github.com/Immediate-Mode-UI/layout.c ) (e.g. for cross-node animations etc.). That's very cool and I'm glad this successful approach works on web too!

And yes, I meant also structural changes, so many thanks for the pointer to tag-params as that seems to fit the use case pretty well.
