### ISSUE TITLE
Recursive call inside `map` results in lost nodes.

### ISSUE THREAD

**Issue by 50kudos** [WebReflection/uhtml#33]
Hi, thanks for making this library. I'm trying if `uhtml` is suitable for highly dynamic DOM generation, so I'm trying with a basic recursion and get a weird result. The second call seems to lost `<li></li>` tag and only string get joined with comma inside `map`.

```html
<html>
  <head>
    <script type="module">
      import {render, html} from 'https://unpkg.com/uhtml?module';
      const data = ["Aa", "Bb", "Cc", "Dd", ["Ee", "Ff"]]

      const render_html = (d) => {
      	return html`
          <ul>
            ${d.map(a => {
              if (a.isArray) return html`<li>${render_html(a)}</li>`
              else return html`<li>${a}</li>`
            })}
          </ul>
      	`
      }
      render(document.body, render_html(data))
    </script>
  </head>
  <body>
  </body>
</html>
```

## Actual result:

- Aa
- Bb
- Cc
- Dd
- Ee,Ff

## Expected result:

- Aa
- Bb
- Cc
- Dd
  - Ee
  - Ff

**Comment by WebReflection** [comment]
`Array.isArray(a)` ... no `a.isArray` ... `a.isArray` is not JavaScript, it doesn't exist, it's undefined, you never enter that `if` statement.

**Comment by WebReflection** [comment]
P.S. yes, `uhtml` works with everything highly dynamic, it's been in production for a while and [DBMonster](https://github.com/WebReflection/uhtml/blob/master/test/dbmonster.html) might give you a hint it has zero issues with nested values.

[live demo](https://webreflection.github.io/uhtml/test/dbmonster.html) 👋

**Comment by 50kudos** [comment]
I just woke up and immediately realized my mistake last night, about to come to close issue myself. But it's too late! It's like I was drunk last night, sorry about that!

**Comment by WebReflection** [comment]
Well, if it gives you any relief it took me way longer than expected to notice that myself ... no shame, all good, it happens 👋
