### ISSUE TITLE
HTML Entities

### ISSUE THREAD

**Issue by CaptainJKoB** [WebReflection/uhtml#34]
Hello,

I came across some behaviour I wasn't sure if it is intentional or not.
If a HTML Entity is inside a variable that is later rendered the entity is kept as is.

Example:
```javascript
import { html, render } from "uhtml";

const entityString = 'Tom &amp; Jerry';

render(document.body, html`
  <span>${ entityString }</span>
  </br>
  <span>Tom &amp; Jerry</span>
`);
```

Expected output(?):
```
Tom & Jerry
Tom & Jerry
```

Current output:
```
Tom &amp; Jerry
Tom & Jerry
```

Is this behaviour desirable? Or did i miss something?

Thank you.

**Comment by WebReflection** [comment]
yes, `uhtml` is safely escaped by default, and in this very specific case, it sets the `entityString` as node `textContent`, which is also safe by default.

You can't have `html` in interpolations, but you could use the `ref=${node => {...}}` to do so at your own risk:

```js
import { html, render } from "uhtml";

const entityString = 'Tom &amp; Jerry';

render(document.body, html`
  <span ref=${node => { node.innerHTML = entityString; }} />
  </br>
  <span>Tom &amp; Jerry</span>
`);
```
