### ISSUE TITLE
Is it safe against XSS?

### ISSUE THREAD

**Issue by PeteSolid** [WebReflection/uhtml#5]
Hi, sorry if this might be a rather trivial question:

I am using a CSP server and use DOMPurify to protect the tagged templates. Sadly, this is removing all the EventListener on the HTMLElements. 
So what would you do in order to have safe code but also make good use of this Library?
Thank you 😊

**Comment by WebReflection** [comment]
This library is safe by default, not sure what you mean.
Closing as there's no action to take, but please feel free to expand and write in here.
