### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by ivantacca** [WebReflection/uhtml#53]
Hello, we are experiencing this issue on our web app:
sometimes, when we have state changes and `update()` is fired, the entire app stop working and the console shows this error:

`Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

We are trying to find a workaround for this problem and we will send a PR once solved

**Comment by WebReflection** [comment]
no much time these days and not convinced I want to fix this as it's a 3rd party issue, not a uhtml one. Closing for now.
