### ISSUE TITLE
Question about components (not web components)

### ISSUE THREAD

**Issue by FbN** [WebReflection/uhtml#55]
I have recently been approaching the lib coming from vdom based libs.

I see I can simply declare components like

```js
const li = v => html`<li class="test">${v}</li>`

const ul = list => html`<ul class="test">${list.map(li)}</ul>`
```

Is there a way to attache an event listerner to a component (the result of the function) and be able intercept only events from that component?
Try to explain the API I would like to obtain
```js
const isolate =  component => {
   //...
   return {
       component: ...,
       on: selector => event => callback => {
         // .... return unsubsribe
         }
   }
}

const LI = v => html`<li class="test">${v}</li>`

const UL = list => html`<ul class="test"><li>ADD</li>${list.map(isolate(LI))}</ul>`

const {ul, on} = isolate(UL)

on('li')('click')(console.log)
```
Then the delegate (on the UL? and if I have other siblings?) would act on events on the first <li> but not on other because owned by different components.

Any suggestion on how to obtain something similar? I think I can hack the template strings and add ref="" to root elements to react to element creations and mark root elements of components in some way. Or there are better solutions?

**Comment by WebReflection** [comment]
if you come from vdom ... maybe you come from P/React and/or hooks? In that case, have you checked [uland](https://github.com/WebReflection/uland#readme) ?

**Comment by FbN** [comment]
Thank you for the quick reply. I Looked at uland but I dont want to use on* events directly as attribute on elements. With ref= is possible to know when an element is created and attached to DOM. Is there a way to know when an element is removed from the DOM? If yes I think I can build the API as above

**Comment by WebReflection** [comment]
how did you hook into elements lifecycle before? nothing really different here ... but curious to know ... anyway, `MutationObserver` is there to help out with connected/disconnected things, but it requires your own integration here

**Comment by FbN** [comment]
I have used Snabbdom which have hooks for lifecycle events like node
insertion update and removal https://github.com/snabbdom/snabbdom#hooks

Il lun 1 nov 2021, 21:54 Andrea Giammarchi ***@***.***> ha
scritto:

**Comment by WebReflection** [comment]
I see ... well, I have an alternative here: https://github.com/WebReflection/lighterhtml-plus#lighterhtml-plus

maybe one day I'll have the same in *uhtml* too ... the thing is, when those events matter, I usually go for Custom Elements right away, either builtin extend or regular

**Comment by FbN** [comment]
I realized that ref=${callback} the callback is called with the element but befor it is attached to the DOM (when it's still resident on the document fragment). So I cannot access the node parent using ref=. Is it the desired behaviour?

**Comment by WebReflection** [comment]
Yes, because none of the things you are doing are documented as such for `ref` ... *connected* and *disconnected* are a different beast, but you can use `ref` to hook your node into that loop, still I don't know why you need it so desperately

**Comment by FbN** [comment]
I want to attach a event listener to the parent of an html`<><><><>` result  to capture events coming from the generated node in a programmatic way (to construct isolated components). This without any explict attribute wrote directly on html code or visible custom elements. 

Something like
```js
html`<div >${onButtonClick(callback)(html`<button  /><button /><button />`)}</div>`
```

**Comment by WebReflection** [comment]
you can do that via `<div onclick=${callback}>` ... not sure why you are trying to avoid what's uhtml all about 🤔

**Comment by FbN** [comment]
Because with onclick I have to declare events binding when I wrote html.
Instead I want to separate events binding in a later step.

Il gio 4 nov 2021, 07:29 Andrea Giammarchi ***@***.***> ha
scritto:

**Comment by WebReflection** [comment]
then I believe custom elements are the primitive you're looking for ... see [uce](https://github.com/WebReflection/uce#readme), [ube](https://github.com/WebReflection/ube#readme), or [p-cool elements](https://github.com/WebReflection/p-cool#readme)

**Comment by FbN** [comment]
Thank you I will give a look, so many projects. Sorry I found only now the
discussion thread (https://github.com/WebReflection/discussions/discussions)
that would be a better place to ask than this issue. I'll close it and open
a discussion if I have other questions. Thank you very much for your
support.
