### ISSUE TITLE
Uncaught bad template

### ISSUE THREAD

**Issue by Dan-Do** [WebReflection/uhtml#57]
I am not sure where is the error. Please look at this https://codepen.io/ali33yukisakura/pen/JjOodXK?editors=1011

**Comment by WebReflection** [comment]
partial attributes are not supported in uhtml (neither in native DOM) ... so you need to write this:

```html
<div class="${'modal-card modal-' + this.props.size}">
```

not this

```html
<div class="modal-card modal-${this.props.size}">
```
