### ISSUE TITLE
Object attribute support

### ISSUE THREAD

**Issue by abdolian** [WebReflection/uhtml#61]
I need something like `.dataset=${object}` without `data-` prefix.

Input
`<div .attr="${{foo: 1, 'foo-bar': 2}}"></div>`

Output
`<div foo="1" foo-bar="2"></div>`

**Comment by WebReflection** [comment]
easy with custom elements ... you define a getter, and set an attribute per each object key/value pair ... otherwise, check [uhtml-intents](https://github.com/WebReflection/uhtml-intents#readme)
