### ISSUE TITLE
node is not instanceof HTMLElement when imported from uhtml v3

### ISSUE THREAD

**Issue by dbauszus-glx** [WebReflection/uhtml#64]
I upgraded uhtml to v3 in my package.json and then build the library using esbuild.

I import uhtml like so but nodes from tagged html.node are not instanceof HTMLElement. This printed true when I install uhtml@2.8

```js
import {render, html, svg} from 'uhtml'

let node = html.node`<div>Foo`

console.log(node instanceof HTMLElement) //false
```

Oddly though I tried to test this in a codepen and everything worked as expected.

uhtm@2.8 as well as 3.0 both return the node as instanceof HTMLElement.

```js
// import { html } from "https://unpkg.com/uhtml@2.8.0/esm/index.js?module";

import { html } from "https://unpkg.com/uhtml@3.0.0/esm/index.js?module";

let node = html.node`<div>Foo`

console.log(node instanceof HTMLElement) //true
```

Not really sure what I am doing wrong or how to better decribe the issue.

Anyways. Not a biggie since we are super happy with uhtml@2.8 but maybe something we can look into at our side.

**Comment by WebReflection** [comment]
So … the bug is about code that works as expected? I’ve no idea how to help here.

The parser is different and it might be the culprit … try older uparser with uhtml 3 or just stick with uhtml 2 until you understand what’s failing and how I can reproduce it?

**Comment by vimtaai** [comment]
We ran into the same issue. The `html.node` function does not return an `HTMLElement` instance in our codebase when we import it from NPM and bundle it with webpack. However, if we load the package from a CDN, it does. The version is 3.0.0 in both cases.

**Comment by dbauszus-glx** [comment]
I can confirm this. I just double checked my production code. Unfortunately we use the empty line a lot at the beginning of tagged templates.

**Comment by WebReflection** [comment]
It was a *uparser* issue which has now been fixed (and covered).

Apologies for the inconvenient.

**Comment by vimtaai** [comment]
Thanks for the quick fix, @WebReflection <3
