### ISSUE TITLE
Incompatible with NextJs

### ISSUE THREAD

**Issue by abdolian** [WebReflection/uhtml#65]
I've created a custom element based on **Uhtml** and imported it into the **NextJs** app. I faced with this error: 

![image](https://user-images.githubusercontent.com/43126626/168014718-4aea789a-c0b7-40fc-a622-3f72a26e644d.png)

Do you have any plans for **SSR** support? I need it urgently.

**Comment by danielweck** [comment]
Have you tried this?
https://github.com/WebReflection/uhtml-ssr

**Comment by WebReflection** [comment]
You mean ... [uhtml-ssr](https://github.com/WebReflection/uhtml-ssr#readme) 🤔

**Comment by abdolian** [comment]
SSR is different, try this on a NextJs App:

``` tsx
import type { NextPage } from 'next';
import { render } from 'uhtml';

const Home: NextPage = () => {
  console.log(render)
  return null
};

export default Home;
```

You'll receive an error that is related to DOM

**Comment by WebReflection** [comment]
@abdolian *uhtml* uses the DOM to create templates and elements, I've no idea how you expect it to work without a `document` in it so ... if it's SSR you are after, there is [uhtml-ssr](https://github.com/WebReflection/uhtml-ssr#readme).

If NextJs has a `document` hidden behind a fake global `self` or `window` then I might pass through that, although this is not a bug of this library, this is how the DOM works.
