### ISSUE TITLE
"bad template" but why?

### ISSUE THREAD

**Issue by fopsdev** [WebReflection/uhtml#69]
Hi there

Not sure why i get a "bad template" message on this one:

```
let content = html`<div>
  <caption>
    Hurray
  </caption>
  <div class="fd-table__header">
    <tr class=${`someClass`}></tr>
  </div>
</div> `;
render(document.getElementById("app"), content);
```

It's highly possible i'm doing something stupidly wrong :)

When removing the root ```<div>``` it will work

https://codesandbox.io/s/compassionate-benji-zn94ke?file=/src/index.js

**Comment by WebReflection** [comment]
a TR inside a DIV makes literally zero sense by HTML standards.

**Comment by fopsdev** [comment]
Whoa, fastest answer i've ever got :)
But why is it not failing when removing the root div?

Btw. i've changed it so it uses tbody instead of the div. the div just got there because i was fiddling/testing around

and i needed to do that because i have my own custom elements which renders a table nicely using separate custom element for each row.
(just saying that because i know the structure looks maybe a bit ugly)

**Comment by WebReflection** [comment]
P.S. if you'd like to complain about Safari choice around making certain elements not possible to extend [please do](https://bugs.webkit.org/show_bug.cgi?id=182671#c19) as your case has been raised already by everyone in the field.

**Comment by fopsdev** [comment]
Ok thanks. Makes sense to me now👍
I like how your lib helps me to understand html better :)
