### ISSUE TITLE
Bug with textnodes/tags in a component in jsx

### ISSUE THREAD

**Issue by berlinfox** [WebReflection/uhtml#75]
I was playing around with `x.js` and found (at least for me) a minor bug. Here is my example:
```jsx
import { render } from "https://esm.sh/uhtml@3.0.1/esm/x.js";

function MyElement({ children }) {
  return <div>{children}</div>;
}

render(
  document.querySelector("#test"),
  <MyElement>
    Some Text <b>and some more text</b>
  </MyElement>,
);
```

The result is a concatenated string inside the div element:
```html
<div>Some Text ,[object HTMLElement]<!--isµ0--></div>
```

Adding a fragment around the text node fixes the issue.

```jsx
<MyElement>
  <>Some Text </>
  <b>and some more text</b>
</MyElement>
```

**Edit:** and this works, too:

```jsx
<MyElement>
  {html`Some Text <b>some more text</b>`}
</MyElement>
```

**Comment by WebReflection** [comment]
closing here as this is likely a jsx2tag issue, the x.js doesn't really do much and html itself works, as you stated

**Comment by WebReflection** [comment]
It shuold be up and running 👋
