### ISSUE TITLE
Bug: texContent -> textContent

### ISSUE THREAD

**Issue by greghuc** [WebReflection/uhtml#88]
I tracked back a v4 error to https://github.com/WebReflection/uhtml/blob/main/esm/handler.js#L179

'texContent' should be 'textContent'

**Comment by WebReflection** [comment]
thanks ... I really should bring back tests and coverage ... it's just that linkedom might not have it all for the SVG case but I will eventually do that ... everything else has been manually tested (except this one, apologies).

Fixed in latest.

**Comment by greghuc** [comment]
@WebReflection no worries, and thanks for uhtml. It's great.

**Comment by WebReflection** [comment]
@greghuc just FYI the 100% linkedom based test coverage is back with even more tests so I hope stability now is at pair with what I had before. Most test pages have been updated too (just swapped global leak with a proper module) and everything looks fine to me. Thanks for your patience.

**Comment by greghuc** [comment]
@WebReflection that's great there are more tests. I always feel more confident refactoring when I know tests will catch the breakages. I've switched my main app to use v4, so will look out for any more issues.
