### ISSUE TITLE
Cannot render empty array

### ISSUE THREAD

**Issue by lazex** [WebReflection/uhtml#91]
If the array is empty, render is failed.

```js
import { html, render } from "uhtml"

render(
  document.querySelector('#app'),
  html`
    <h1>foo</h1>
    <div>${[]}</div>
  `
)
```

The error is here.

```
Failed to execute 'setStartBefore' on 'Range': parameter 1 is not of type 'Node'.
```

**Comment by WebReflection** [comment]
Ooops, silly mistake, fixed, thanks!

**Comment by WebReflection** [comment]
to clarify, this issue was happening *only* if you start with an empty array ... now that's fixed, changing from non-empty to empty then non-empty again worked well, sorry for the issue.
