### ISSUE TITLE
V4 crashes on empty array

### ISSUE THREAD

**Issue by gbishop** [WebReflection/uhtml#98]
My `grid` component can sometimes be empty. The simplified version of the template is
```javascript
    const body = html`<div style=${styleString(style)}>${result}</div>`;
```
Where result is an array of Holes. If that array happens to be empty, I get a crash with the message

    Error: Failed to execute 'setEndAfter' on 'Range': the given Node has no parent. rendering Page UI

I can easily work around by making sure it isn't empty. This template is used to render different grids on various tabs in the interface.

**Comment by WebReflection** [comment]
In your example nothing is an array so I don’t get it as arrays are working and code covered 100%

**Comment by WebReflection** [comment]
That case array empty then filled then empty again is also covered so please write a minimal example of your issue or I won’t know where to look at, thank you

**Comment by gbishop** [comment]
I'll work on boiling it down to something you can debug on.

**Comment by gbishop** [comment]
Here is a small example that illustrates the issue. Click on any of the buttons to see it fail. It dies on the second render.

```javascript
import { html, render } from "uhtml";

function grid(n) {
  const cells = [];
  for (let i = 0; i < n; i++) {
    cells.push(cell(i));
  }
  const grid = html`<div class="grid">${cells}</div>`;
  return grid;
}

function cell(i) {
  const content = [html`<span>C</span>`, html`<span>${i}</span>`];
  return html`<button>${content}</button>`;
}

let n1 = 36;
let n2 = 0;

function page() {
  return html`<div
    class="page"
    onclick=${() => {
      n1 = 0;
      n2 = 63;
      draw();
    }}
  >
    ${grid(n1)} ${grid(n2)}
  </div> `;
}

function draw() {
  render(document.body, page());
}

draw();
```

**Comment by WebReflection** [comment]
this is odd ... I have tests around `[]` as new hole content but I'll surely have a look, thank you for the minimal example!

**Comment by gbishop** [comment]
The key (I think) is that the buttons contain arrays. I couldn't get it to fail until I added that. So this is an array of holes that themselves contain arrays.

**Comment by WebReflection** [comment]
it's posible this comes from v3 too then, otherwise it's a regression.

**Comment by gbishop** [comment]
I updated the example above replacing the large number of buttons with 1 in each case. That is sufficient to trigger the bug and likely easier to examine the internals.

**Comment by WebReflection** [comment]
Fixed ... I was too smart with that fast path ... of course fragments would break the world with previous logic ...

**Comment by gbishop** [comment]
Thanks. Working now.
